### ISSUE TITLE
error create folder in fat or usb 0

### ISSUE THREAD

**Issue by bonna79** [SwedishGojira/MiSTer-scripts#4]
when I run the script to install US or JP bios it gives me login errors. so it doesn't create folders for me. forss am I wrong? I'll add a photo if I can to help you understand better.
![Schermata 2023-06-11 alle 17 56 43](https://github.com/SwedishGojira/MiSTer-scripts/assets/70318818/788a3d0d-c969-44d0-af88-846733887e4c)

**Comment by SwedishGojira** [comment]
Are you running the script on your actual MiSTer, placed in the scripts folder and using the scripts menu?
Also the script is detecting that you have two Saturn folders. One on the USB and one on the SD card. You should only have one folder.

**Comment by bonna79** [comment]
> Are you running the script on your actual MiSTer, placed in the scripts folder and using the scripts menu?
> 
> Also the script is detecting that you have two Saturn folders. One on the USB and one on the SD card. You should only have one folder.

That's right . The script is located on the micro sd , inside the scripts folder , from the menu I run the script , but it always returns that error to me . Yet I can read and write the folder. I don't understand if it's a permit problem or something else. I will try to delete the Saturn folder, on the micro sd, because I keep everything on the external pen drive. If I solve it like this, I'll let you know.

Thank you

**Comment by eewokee** [comment]
Similar with me. The script does not create a folder

**Comment by SwedishGojira** [comment]
How did you guys download and transfer the script to the MiSTer? Those question mark blocks should not be showing if you downloaded the script and transferred it properly.
Did you guys perhaps copy paste the text to a new file instead of downloading the raw script?

**Comment by eewokee** [comment]
No, downloaded the github zip file. I transferred via sdcard and ftp. Both gave me a similar message as the one above.

**Comment by SwedishGojira** [comment]
eewokee: Do you possibly have two "saturn" folders on your mister?

The screenshot from bonna79 above indicates that the script have detected two saturn folders on the MiSTer, indicated by the [X] in the list. Do you also have these double [X] when you run the script?

**Comment by eewokee** [comment]
I had two folders indeed. I deleted the one on the fat drive.

**Comment by SwedishGojira** [comment]
Did the script work after that?

**Comment by eewokee** [comment]
No, unfortunately not.

**Comment by SwedishGojira** [comment]
Do you also have the "question blocks" in the text when you run the script?

**Comment by eewokee** [comment]
Yes, I have those too.

**Comment by SwedishGojira** [comment]
Could you try to open [this link](https://raw.githubusercontent.com/SwedishGojira/MiSTer-scripts/main/saturn-us-bios-installer.sh), then right click it and choose "save page as" and then save it to file. You should get a file named "saturn-us-bios-installer.sh". Then transfer that file to your script directory on the MiSTer and see if you get the same result when you run it.

**Comment by eewokee** [comment]
Unfortunately the same result. 
![Uploading IMG_1636.jpeg…]()

**Comment by eewokee** [comment]
![IMG_1636](https://github.com/SwedishGojira/MiSTer-scripts/assets/68441974/febf3069-0c7d-456b-9f1d-f8e0d6627d78)

**Comment by bonna79** [comment]
Idem io , scaricato lo script da ghithub, copiato via ftp su micro sd , riavviato là mister , ma il problema rimane . Non riesce e creare la cartella . Inviato da iPhoneIl giorno 18 set 2023, alle ore 15:35, eewokee ***@***.***> ha scritto:﻿
I had two folders indeed. I deleted the one on the fat drive.

**Comment by SwedishGojira** [comment]
I have changed a few things in the scripts this morning. I had accidentally left out a variable in the script, but somehow it was still working on my system. Hopefully it will work as supposed to now.

**Comment by bonna79** [comment]
Ok 👍 perfetto Stasera scarico la nuova versione dell o script e provo Grazie Ok 👍 perfectTonight I download the new version of the script and tryThank you Il giorno 25 set 2023, alle ore 12:02, Andreas Svalås ***@***.***> ha scritto:﻿
Please try to run the script now.
I have changed a few things in the scripts this morning. I had missed a variable, but somehow it was still working on my system.

**Comment by SwedishGojira** [comment]
I have changed a few things in the scripts this morning. I had accidentally left out a variable in the script, but somehow it was still working on my system. Hopefully it will work as supposed to now.

**Comment by eewokee** [comment]
I can confirm it now works like a charm!! Thanks!

**Comment by SwedishGojira** [comment]
Thank you eewokee. I will await confirmation from bonna79 also before I close the issue.

Thanks to you guys I will also put in a warning if other people also have two Saturn folders in a future revision.

**Comment by bonna79** [comment]
Funziona perfettamente provato ad usare tuti gli script per scaricare i bios e vanno perfettamente . Grazie mille 🙏 Allego foto It works perfectly tried to use all the scripts to download the bios and they go perfectly. Thank you very much 🙏I am attaching photosInviato da iPhoneIl giorno 25 set 2023, alle ore 13:53, Andreas Svalås ***@***.***> ha scritto:﻿
Thank you eewokee. I will await confirmation from bonna79 also before I close the issue.
Thanks to you guys I will also put in a warning if other people also have two Saturn folders in a future revision.
